[tool.poetry]
name = "test-project"
version = "0.1.0"
description = ""
authors = ["Climatiq <info@climatiq.io>"]

[tool.poetry.dependencies]
python = "^3.7.1"
oefdb = "*"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "test-pypi"
url = "https://test.pypi.org/simple/"
