name: Python

on: push

jobs:
  test:
    name: Lint and run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 3.7,3.8,3.9 ]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Lint
        run: poetry run poe lint

      - name: Run tests
        run: poetry run poe pytest
